name: Deploy to Azure App Service

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build and publish
      run: |
        dotnet publish -c Release -o $GITHUB_WORKSPACE/myapp
        
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        app-name: 'ameyplayground'
        package: './myapp'
